name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Build steps
      - name: Build site
        run: |
          mkdir -p dist
          cp -r $(ls -A | grep -v '^dist$') dist/

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true
          enable_jekyll: false

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${pr.number}/`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `Preview: ${url}`
            });
